In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score
from xgboost import XGBClassifier
from sklearn import metrics
import warnings
warnings.filterwarnings("ignore")

In [53]:
train=pd.read_csv('Train.csv')
train.head()

INCIDENT_ID       DATE  X_1  X_2  X_3  X_4  X_5  X_6  X_7  X_8  X_9  X_10  \
0   CR_102659  04-JUL-04    0   36   34    2    1    5    6    1    6     1   
1   CR_189752  18-JUL-17    1   37   37    0    0   11   17    1    6     1   
2   CR_184637  15-MAR-17    0    3    2    3    5    1    0    2    3     1   
3   CR_139071  13-FEB-09    0   33   32    2    1    7    1    1    6     1   
4   CR_109335  13-APR-05    0   33   32    2    1    8    3    0    5     1   

   X_11  X_12  X_13  X_14  X_15  MULTIPLE_OFFENSE  
0   174   1.0    92    29    36                 0  
1   236   1.0   103   142    34                 1  
2   174   1.0   110    93    34                 1  
3   249   1.0    72    29    34                 1  
4   174   0.0   112    29    43                 1

In [54]:
train.describe(include="all")

INCIDENT_ID       DATE           X_1           X_2           X_3  \
count        23856      23856  23856.000000  23856.000000  23856.000000   
unique       23856       9121           NaN           NaN           NaN   
top        CR_9623  12-SEP-01           NaN           NaN           NaN   
freq             1         22           NaN           NaN           NaN   
mean           NaN        NaN      0.483778     24.791206     24.637450   
std            NaN        NaN      1.439738     15.240231     15.135093   
min            NaN        NaN      0.000000      0.000000      0.000000   
25%            NaN        NaN      0.000000      7.000000      8.000000   
50%            NaN        NaN      0.000000     24.000000     24.000000   
75%            NaN        NaN      0.000000     36.000000     35.000000   
max            NaN        NaN      7.000000     52.000000     52.000000   

                 X_4           X_5           X_6           X_7           X_8  \
count   23856.000000  23856.000000  23856.000000  23856.000000  23856.000000   
unique           NaN           NaN           NaN           NaN           NaN   
top              NaN           NaN           NaN           NaN           NaN   
freq             NaN           NaN           NaN           NaN           NaN   
mean        4.276744      2.455609      6.154175      4.876509      0.972460   
std         2.944672      1.963095      4.471756      3.881931      1.453144   
min         0.000000      0.000000      1.000000      0.000000      0.000000   
25%         2.000000      1.000000      3.000000      2.000000      0.000000   
50%         4.000000      3.000000      5.000000      4.000000      1.000000   
75%         6.000000      5.000000      8.000000      7.000000      1.000000   
max        10.000000      5.000000     19.000000     18.000000     99.000000   

                 X_9          X_10          X_11          X_12          X_13  \
count   23856.000000  23856.000000  23856.000000  23674.000000  23856.000000   
unique           NaN           NaN           NaN           NaN           NaN   
top              NaN           NaN           NaN           NaN           NaN   
freq             NaN           NaN           NaN           NaN           NaN   
mean        4.924128      1.244802    206.954519      0.974064     85.237383   
std         1.362625      1.119301     93.033348      1.167725     27.597226   
min         0.000000      1.000000      0.000000      0.000000      0.000000   
25%         5.000000      1.000000    174.000000      1.000000     72.000000   
50%         5.000000      1.000000    249.000000      1.000000     98.000000   
75%         6.000000      1.000000    249.000000      1.000000    103.000000   
max         6.000000     90.000000    332.000000     90.000000    116.000000   

                X_14          X_15  MULTIPLE_OFFENSE  
count   23856.000000  23856.000000      23856.000000  
unique           NaN           NaN               NaN  
top              NaN           NaN               NaN  
freq             NaN           NaN               NaN  
mean       72.674296     33.464747          0.955231  
std        43.297320      8.386834          0.206800  
min         0.000000      0.000000          0.000000  
25%        29.000000     34.000000          1.000000  
50%        62.000000     34.000000          1.000000  
75%       107.000000     34.000000          1.000000  
max       142.000000     50.000000          1.000000

In [55]:
train.isna().sum()
train['MULTIPLE_OFFENSE'].value_counts()

1    22788
0     1068
Name: MULTIPLE_OFFENSE, dtype: int64

In [56]:
train.fillna(0,inplace=True)
train.head()

INCIDENT_ID       DATE  X_1  X_2  X_3  X_4  X_5  X_6  X_7  X_8  X_9  X_10  \
0   CR_102659  04-JUL-04    0   36   34    2    1    5    6    1    6     1   
1   CR_189752  18-JUL-17    1   37   37    0    0   11   17    1    6     1   
2   CR_184637  15-MAR-17    0    3    2    3    5    1    0    2    3     1   
3   CR_139071  13-FEB-09    0   33   32    2    1    7    1    1    6     1   
4   CR_109335  13-APR-05    0   33   32    2    1    8    3    0    5     1   

   X_11  X_12  X_13  X_14  X_15  MULTIPLE_OFFENSE  
0   174   1.0    92    29    36                 0  
1   236   1.0   103   142    34                 1  
2   174   1.0   110    93    34                 1  
3   249   1.0    72    29    34                 1  
4   174   0.0   112    29    43                 1

In [57]:
test=pd.read_csv("Test.csv")
test.head()
ynew=test.INCIDENT_ID
ynew.head()
test=test.drop(["DATE"],axis=1)
test1=test.drop(["INCIDENT_ID"],axis=1)
test1.head()

X_1  X_2  X_3  X_4  X_5  X_6  X_7  X_8  X_9  X_10  X_11  X_12  X_13  X_14  \
0    0   30   35    7    3    6    4    0    5     1   174   NaN    72   119   
1    0   44   44    1    3    7    1    4    6     1   316   0.0    12    29   
2    0   34   33    3    5    2    7    3    0     1   316   1.0    72     0   
3    7    3    2    3    5    9    8    0    5     1   174   1.0   112    87   
4    0    7    8    7    3    2    7    1    5     1   174   0.0   112    93   

   X_15  
0    23  
1    34  
2    34  
3    34  
4    43

In [58]:
train.isna().sum()

INCIDENT_ID         0
DATE                0
X_1                 0
X_2                 0
X_3                 0
X_4                 0
X_5                 0
X_6                 0
X_7                 0
X_8                 0
X_9                 0
X_10                0
X_11                0
X_12                0
X_13                0
X_14                0
X_15                0
MULTIPLE_OFFENSE    0
dtype: int64

In [59]:
x=train.drop(["MULTIPLE_OFFENSE"],axis=1)
x=x.drop(["DATE"],axis=1)

In [60]:

x=x.drop(["INCIDENT_ID"],axis=1)
x.head()


X_1  X_2  X_3  X_4  X_5  X_6  X_7  X_8  X_9  X_10  X_11  X_12  X_13  X_14  \
0    0   36   34    2    1    5    6    1    6     1   174   1.0    92    29   
1    1   37   37    0    0   11   17    1    6     1   236   1.0   103   142   
2    0    3    2    3    5    1    0    2    3     1   174   1.0   110    93   
3    0   33   32    2    1    7    1    1    6     1   249   1.0    72    29   
4    0   33   32    2    1    8    3    0    5     1   174   0.0   112    29   

   X_15  
0    36  
1    34  
2    34  
3    34  
4    43

In [61]:
y=train.MULTIPLE_OFFENSE

y.head()
y.shape

(23856,)

In [74]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.4,random_state=582)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_test1 = sc.transform(test1)
X_test2 = sc.transform(test1)
X_train.shape

(14313, 15)

In [75]:
from imblearn.combine import SMOTETomek
nm = SMOTETomek()
X_train,y_train=nm.fit_sample(X_train,y_train)
X_train.shape
y_train.value_counts()

1    13681
0    13681
Name: MULTIPLE_OFFENSE, dtype: int64

In [76]:
model = XGBClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
XGB=metrics.accuracy_score(y_pred, y_pred)*100
print('Results using XGBoost Classifier is')
print('Accuracy :',XGB)
print('Precision :',metrics.precision_score(y_test,y_pred))
print('Recall :',metrics.recall_score(y_test,y_pred))
print('Area Under ROC Curve',metrics.roc_auc_score(y_test,y_pred))
cm = confusion_matrix(y_test,y_pred)
cm
y_pre = model.predict(X_test1)


Results using XGBoost Classifier is
Accuracy : 100.0
Precision : 0.999559277214632
Recall : 0.9963756177924218
Area Under ROC Curve 0.9936215988505487


In [77]:
svm = SVC() 
svm.fit(X_train,y_train)
p = svm.predict(X_test)
SVM=metrics.accuracy_score(y_test, p)*100
print('Results using Support Vector Machine Classifier is')
print('Accuracy :',SVM)
print('Precision :',metrics.precision_score(y_test,p))
print('Recall :',metrics.recall_score(y_test,p))
print('Area Under ROCCurve',metrics.roc_auc_score(y_test,p))
cm = confusion_matrix(y_test,p)
cm



Results using Support Vector Machine Classifier is
Accuracy : 94.6662475112648
Precision : 0.9923253150057274
Recall : 0.9514552443712246
Area Under ROCCurve 0.8992436039207722


array([[ 371,   67],
       [ 442, 8663]], dtype=int64)

In [78]:
clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_train,y_train)
p = clf.predict(X_test)
RF=metrics.accuracy_score(y_test, p)*100
print('Results using Random Forest Classifier is')
print('Accuracy :',RF)
print('Precision :',metrics.precision_score(y_test,p))
print('Recall :',metrics.recall_score(y_test,p))
print('Area Under ROC Curve',metrics.roc_auc_score(y_test,p))
cm = confusion_matrix(y_test,p)
cm

Results using Random Forest Classifier is
Accuracy : 99.20360473645604
Precision : 0.9948481859037597
Recall : 0.9968149368478858
Area Under ROC Curve 0.9447545003874132


array([[ 391,   47],
       [  29, 9076]], dtype=int64)

In [79]:
Accuracy=[]
Accuracy.append(XGB)
Accuracy.append(SVM)
Accuracy.append(RF)
Accuracy

[100.0, 94.6662475112648, 99.20360473645604]

In [80]:
ynew=test.INCIDENT_ID

In [83]:
X_test1

array([[-0.33679476,  0.34436525,  0.68800198, ..., -0.47389904,
         1.06852133, -1.25793641],
       [-0.33679476,  1.26598717,  1.28467582, ..., -2.63732489,
        -1.01150575,  0.05846084],
       [-0.33679476,  0.6076858 ,  0.5554078 , ..., -0.47389904,
        -1.6817367 ,  0.05846084],
       ...,
       [-0.33679476,  0.0810447 ,  0.15762524, ..., -0.47389904,
        -0.24882916,  0.05846084],
       [-0.33679476, -0.24810598, -0.10756313, ...,  0.24724291,
        -0.24882916,  0.05846084],
       [-0.33679476, -1.36721831, -1.36720789, ..., -0.47389904,
        -1.01150575,  0.05846084]])

In [84]:
y_pred = model.predict(X_test1)

In [88]:
df=pd.DataFrame(data=ynew)
df['MULTIPLE_OFFENSE']=y_pre
df.head()


INCIDENT_ID  MULTIPLE_OFFENSE
0   CR_195453                 1
1   CR_103520                 1
2   CR_196089                 1
3   CR_112195                 1
4   CR_149832                 1

In [87]:
df.to_csv("submission.csv")
